name: Build And Push
on:
  push:
    tags:        
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Environment Variable
        id: vars
        run: echo "::set-output name=build_version::$(git describe --tags)"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./deploy/Dockerfile
          platforms:  |
            linux/arm
            linux/arm64
            linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bark-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bark-server:${{ steps.vars.outputs.build_version }}
            ghcr.io/dockers-x/bark-server:latest
            ghcr.io/dockers-x/bark-server:${{ steps.vars.outputs.build_version }}
          push: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
